// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_summaryScreen
void ui_summaryScreen_screen_init(void);
lv_obj_t *ui_summaryScreen;
lv_obj_t *ui_cpuArc;
lv_obj_t *ui_cpuMhz;
lv_obj_t *ui_cpuTitle;
lv_obj_t *ui_cpuTemp;
lv_obj_t *ui_cpuRam;
lv_obj_t *ui_gpuArc;
lv_obj_t *ui_gpuRam;
lv_obj_t *ui_gpuTitle;
lv_obj_t *ui_gpuTemp;
lv_obj_t *ui_gpuMhz;
lv_obj_t *ui_topBar;


// SCREEN: ui_cpuTempChartScreen
void ui_cpuTempChartScreen_screen_init(void);
lv_obj_t *ui_cpuTempChartScreen;
lv_obj_t *ui_topBar1;
lv_obj_t *ui_cpuTempChart;


// SCREEN: ui_gpuTempChartScreen
void ui_gpuTempChartScreen_screen_init(void);
lv_obj_t *ui_gpuTempChartScreen;
lv_obj_t *ui_topBar2;
lv_obj_t *ui_gpuTempChart;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_summaryScreen_screen_init();
ui_cpuTempChartScreen_screen_init();
ui_gpuTempChartScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_summaryScreen);
}
