// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "C:\Users\Michele\Documents\Arduino\libraries\lvgl\lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_summaryScreen
void ui_summaryScreen_screen_init(void);
extern lv_obj_t *ui_summaryScreen;
extern lv_obj_t *ui_cpuArc;
extern lv_obj_t *ui_cpuMhz;
extern lv_obj_t *ui_cpuTitle;
extern lv_obj_t *ui_cpuTemp;
extern lv_obj_t *ui_cpuRam;
extern lv_obj_t *ui_gpuArc;
extern lv_obj_t *ui_gpuRam;
extern lv_obj_t *ui_gpuTitle;
extern lv_obj_t *ui_gpuTemp;
extern lv_obj_t *ui_gpuMhz;
extern lv_obj_t *ui_topBar;
// SCREEN: ui_cpuTempChartScreen
void ui_cpuTempChartScreen_screen_init(void);
extern lv_obj_t *ui_cpuTempChartScreen;
extern lv_obj_t *ui_topBar1;
extern lv_obj_t *ui_cpuTempChart;
// SCREEN: ui_gpuTempChartScreen
void ui_gpuTempChartScreen_screen_init(void);
extern lv_obj_t *ui_gpuTempChartScreen;
extern lv_obj_t *ui_topBar2;
extern lv_obj_t *ui_gpuTempChart;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
