// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_TOPBAR_H
#define _UI_COMP_TOPBAR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT topBar
#define UI_COMP_TOPBAR_TOPBAR 0
#define UI_COMP_TOPBAR_TOPBARTITLE 1
#define UI_COMP_TOPBAR_TOPBARDATE 2
#define UI_COMP_TOPBAR_TOPBARCLOCK 3
#define _UI_COMP_TOPBAR_NUM 4
lv_obj_t *ui_topBar_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
