// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT topBar

lv_obj_t *ui_topBar_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_topBar;
cui_topBar = lv_obj_create(comp_parent);
lv_obj_set_width( cui_topBar, 536);
lv_obj_set_height( cui_topBar, 35);
lv_obj_clear_flag( cui_topBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_topBar, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_topBar, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_topBar, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_topBar, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_topBarTitle;
cui_topBarTitle = lv_label_create(cui_topBar);
lv_obj_set_width( cui_topBarTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_topBarTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_topBarTitle, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_topBarTitle,"Riepilogo");
lv_obj_set_style_text_font(cui_topBarTitle, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_topBarDate;
cui_topBarDate = lv_label_create(cui_topBar);
lv_obj_set_width( cui_topBarDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_topBarDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_topBarDate, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_topBarDate,"00/00/00");
lv_obj_set_style_text_font(cui_topBarDate, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_topBarClock;
cui_topBarClock = lv_label_create(cui_topBar);
lv_obj_set_width( cui_topBarClock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_topBarClock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_topBarClock, LV_ALIGN_CENTER );
lv_label_set_text(cui_topBarClock,"00:00");
lv_obj_set_style_text_font(cui_topBarClock, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TOPBAR_NUM);
children[UI_COMP_TOPBAR_TOPBAR] = cui_topBar;
children[UI_COMP_TOPBAR_TOPBARTITLE] = cui_topBarTitle;
children[UI_COMP_TOPBAR_TOPBARDATE] = cui_topBarDate;
children[UI_COMP_TOPBAR_TOPBARCLOCK] = cui_topBarClock;
lv_obj_add_event_cb(cui_topBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_topBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_topBar_create_hook(cui_topBar);
return cui_topBar; 
}

