// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_cpuTempChartScreen_screen_init(void)
{
    ui_cpuTempChartScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_cpuTempChartScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cpuTempChartScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpuTempChartScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar1 = ui_topBar_create(ui_cpuTempChartScreen);
    lv_obj_set_x(ui_topBar1, 0);
    lv_obj_set_y(ui_topBar1, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar1, UI_COMP_TOPBAR_TOPBARTITLE), "CPU");


    ui_cpuTempChart = lv_chart_create(ui_cpuTempChartScreen);
    lv_obj_set_width(ui_cpuTempChart, 425);
    lv_obj_set_height(ui_cpuTempChart, 180);
    lv_obj_set_x(ui_cpuTempChart, 0);
    lv_obj_set_y(ui_cpuTempChart, 17);
    lv_obj_set_align(ui_cpuTempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_cpuTempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_cpuTempChart, 50);
    lv_chart_set_axis_tick(ui_cpuTempChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_cpuTempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_cpuTempChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_obj_set_style_bg_color(ui_cpuTempChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpuTempChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_cpuTempChart, lv_color_hex(0xED1C24), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_cpuTempChart, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_cpuTempChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_cpuTempChart, lv_color_hex(0xED1C24), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_cpuTempChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cpuTempChart, &lv_font_montserrat_18, LV_PART_TICKS | LV_STATE_DEFAULT);

}
