// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_gpuTempChartScreen_screen_init(void)
{
ui_gpuTempChartScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_gpuTempChartScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_gpuTempChartScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpuTempChartScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topBar2 = ui_topBar_create(ui_gpuTempChartScreen);
lv_obj_set_x( ui_topBar2, 0 );
lv_obj_set_y( ui_topBar2, 0 );

lv_label_set_text(ui_comp_get_child(ui_topBar2, UI_COMP_TOPBAR_TOPBARTITLE),"GPU");


ui_gpuTempChart = lv_chart_create(ui_gpuTempChartScreen);
lv_obj_set_width( ui_gpuTempChart, 425);
lv_obj_set_height( ui_gpuTempChart, 170);
lv_obj_set_x( ui_gpuTempChart, 0 );
lv_obj_set_y( ui_gpuTempChart, 15 );
lv_obj_set_align( ui_gpuTempChart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_gpuTempChart, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_gpuTempChart, 50);
lv_chart_set_axis_tick( ui_gpuTempChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_gpuTempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_gpuTempChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_obj_set_style_bg_color(ui_gpuTempChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpuTempChart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_gpuTempChart, lv_color_hex(0x76B900), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_gpuTempChart, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_gpuTempChart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_gpuTempChart, lv_color_hex(0x76B900), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_gpuTempChart, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpuTempChart, &lv_font_montserrat_18, LV_PART_TICKS| LV_STATE_DEFAULT);

}
