// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_musicScreen_screen_init(void)
{
    ui_musicScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_musicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_musicScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar4 = ui_topBar_create(ui_musicScreen);
    lv_obj_set_x(ui_topBar4, 0);
    lv_obj_set_y(ui_topBar4, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar4, UI_COMP_TOPBAR_TOPBARTITLE), "In riproduzione");


    ui_bell1 = lv_img_create(ui_musicScreen);
    lv_img_set_src(ui_bell1, &ui_img_music_png);
    lv_obj_set_width(ui_bell1, 100);
    lv_obj_set_height(ui_bell1, 100);
    lv_obj_set_x(ui_bell1, 10);
    lv_obj_set_y(ui_bell1, 17);
    lv_obj_set_align(ui_bell1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bell1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bell1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_musicArtist = lv_label_create(ui_musicScreen);
    lv_obj_set_width(ui_musicArtist, 423);
    lv_obj_set_height(ui_musicArtist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_musicArtist, 110);
    lv_obj_set_y(ui_musicArtist, 58);
    lv_obj_set_align(ui_musicArtist, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_align(ui_musicArtist, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_musicArtist, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_musicArtist, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_musicArtist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_musicArtist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_musicArtist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicTitle = lv_label_create(ui_musicScreen);
    lv_obj_set_width(ui_musicTitle, 423);
    lv_obj_set_height(ui_musicTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_musicTitle, 110);
    lv_obj_set_y(ui_musicTitle, -25);
    lv_obj_set_align(ui_musicTitle, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_align(ui_musicTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_musicTitle, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_musicTitle, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_musicTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_musicTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_musicTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
