// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_notificationScreen_screen_init(void)
{
    ui_notificationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_notificationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_notificationScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notificationScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar3 = ui_topBar_create(ui_notificationScreen);
    lv_obj_set_x(ui_topBar3, 0);
    lv_obj_set_y(ui_topBar3, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar3, UI_COMP_TOPBAR_TOPBARTITLE), "Notifica");


    ui_bell = lv_img_create(ui_notificationScreen);
    lv_img_set_src(ui_bell, &ui_img_bluebell_png);
    lv_obj_set_width(ui_bell, 100);
    lv_obj_set_height(ui_bell, 100);
    lv_obj_set_x(ui_bell, 10);
    lv_obj_set_y(ui_bell, 17);
    lv_obj_set_align(ui_bell, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bell, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bell, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_notificationBody = lv_label_create(ui_notificationScreen);
    lv_obj_set_width(ui_notificationBody, 426);
    lv_obj_set_height(ui_notificationBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notificationBody, 110);
    lv_obj_set_y(ui_notificationBody, 38);
    lv_obj_set_align(ui_notificationBody, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_align(ui_notificationBody, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_notificationBody, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notificationTitle = lv_label_create(ui_notificationScreen);
    lv_obj_set_width(ui_notificationTitle, 426);
    lv_obj_set_height(ui_notificationTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notificationTitle, 110);
    lv_obj_set_y(ui_notificationTitle, -5);
    lv_obj_set_align(ui_notificationTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_notificationTitle, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(ui_notificationTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_notificationTitle, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}
